providers = ["node"]

[phases.setup]
nixPkgs = [
    "...", 
    "chromium",
    "glib", 
    "nss", 
    "nspr", 
    "atk", 
    "cups", 
    "libdrm", 
    "gtk3", 
    "pango", 
    "cairo", 
    "mesa", 
    "alsa-lib", 
    "xorg.libX11", 
    "xorg.libXcomposite", 
    "xorg.libXdamage", 
    "xorg.libXext", 
    "xorg.libXfixes", 
    "xorg.libXrandr", 
    "xorg.libxcb"
]
